### ISSUE TITLE
"Ignition create" errors with invalid driver-type value supplied: Resource

### ISSUE THREAD

**Issue by vadimeisenbergibm** [IBM/ignition#91]
**Describe the bug**
Running `ignition create app` fails with the following error:
`ERROR: invalid driver-type value supplied: Resource`

**Environment: (please complete the following information where applicable):**
 - OS: Mac OS Catalina
 - Version: 2.0.2 
- Stratoss LM: IBM ALM 2.2

**Comment by dvaccarosenna** [comment]
Same as #83 

Use `ignition create app -t RESOURCE` to get round this

**Comment by vadimeisenbergibm** [comment]
Thanks @dvaccarosenna , it works, closing the issue.
